# Generated by Django 4.0.2 on 2024-06-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movies',
            new_name='genres',
        ),
    ]
